// <auto-generated />
namespace QuizProjectMvc.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ModelsNormalized : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModelsNormalized));
        
        string IMigrationMetadata.Id
        {
            get { return "201602161524319_ModelsNormalized"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
